# Generated by Django 6.0.2 on 2026-02-28 08:49

import django.contrib.postgres.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ObanJob',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state', models.TextField(choices=[('available', 'available'), ('executing', 'executing'), ('completed', 'completed'), ('discarded', 'discarded'), ('scheduled', 'scheduled'), ('retryable', 'retryable'), ('cancelled', 'cancelled')], default='available')),
                ('queue', models.TextField(default='default')),
                ('worker', models.TextField()),
                ('args', models.JSONField(default=dict)),
                ('meta', models.JSONField(default=dict, null=True)),
                ('errors', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, null=True)),
                ('attempted_by', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, null=True)),
                ('attempt', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=20)),
                ('priority', models.IntegerField(default=0)),
                ('inserted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('discarded_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oban_jobs',
                'indexes': [models.Index(fields=['queue'], name='oban_jobs_queue_index'), models.Index(fields=['state'], name='oban_jobs_state_index'), models.Index(fields=['state', 'queue', 'priority', 'scheduled_at', 'id'], name='oban_jobs_main_idx')],
            },
        ),
    ]
