# Generated by Django 6.0.2 on 2026-02-28 08:49


from django.db import migrations
from oban.schema import install_sql


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [migrations.RunSQL(install_sql())]
